version: 0.2
phases:
  install:
    commands:
      - docker buildx create --name containerd --driver=docker-container --driver-opt default-load=true --use
  pre_build:
    commands:
      - pwd
      - cd app
      - ls -al
      - docker version
      - export ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - export ECR_REPO=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME
      - export DOCKER_TAG=$ECR_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - export DOCKER_LATEST=$ECR_REPO:latest
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
      - env
  build:
    commands:
      - >-
        docker buildx build
        --cache-to type=inline,ref=${DOCKER_LATEST},mode=min
        --cache-from type=registry,ref=${DOCKER_LATEST}
        --tag ${DOCKER_TAG}
        --builder=containerd
        --build-arg GIT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION}
        --progress=plain
        .
      - docker tag $DOCKER_TAG $DOCKER_LATEST
      - docker push $DOCKER_TAG
      - docker push $DOCKER_LATEST
  post_build:
    commands:
      - envsubst < Dockerrun.aws.template.json > Dockerrun.aws.json
artifacts:
  base-directory: app
  files:
    - .ebextensions/**/*
    - .platform/**/*
    - Dockerrun.aws.json
