version: 0.2
env:
  secrets-manager:
    SNYK_TOKEN: za-test-snyk/api-token
phases:
  pre_build:
    commands:
      - pwd
      - cd app
      - ls -al
      - docker version
      - export ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - export ECR_REPO=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME
      - export DOCKER_TAG=$ECR_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - export DOCKER_CACHE=$ECR_REPO:latest
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
      # this build runs on an aarch64 image, so use the arm64 snyk binary
      - curl -sSLo /usr/local/bin/snyk https://downloads.snyk.io/cli/stable/snyk-linux-arm64 && chmod +x /usr/local/bin/snyk
      - env
  build:
    commands:
      - docker pull $DOCKER_CACHE || true
      - docker build --cache-from $DOCKER_CACHE --build-arg GIT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION} -t $DOCKER_TAG .
      - snyk container test $DOCKER_TAG --file=Dockerfile --severity-threshold=high
      - docker tag $DOCKER_TAG $DOCKER_CACHE
      - docker push $DOCKER_TAG
      - docker push $DOCKER_CACHE
      # record a snapshot in the Snyk UI for ongoing vulnerability alerts
      - snyk container monitor $DOCKER_TAG --file=Dockerfile --project-name=$ECR_REPO_NAME
  post_build:
    commands:
      - envsubst < Dockerrun.aws.template.json > Dockerrun.aws.json
artifacts:
  base-directory: app
  files:
    - .ebextensions/**/*
    - .platform/**/*
    - Dockerrun.aws.json