-- Supports the composite (run, job) references below, so a referenced run is
-- always a run of the referenced job.
ALTER TABLE public.run
    ADD CONSTRAINT run_id_job_unique UNIQUE (id, job_id);

-- One row per group of student input details reported by the Executor.
-- Identity is natural: the job plus the Executor's opaque correlation id.
CREATE TABLE public.student_input_details (
    job_id INTEGER NOT NULL REFERENCES public.job (id) ON DELETE CASCADE,
    correlation_id TEXT NOT NULL CHECK (length(correlation_id) BETWEEN 1 AND 128),
    -- The run that first established this row. Provenance, not ownership: the
    -- job FK above owns the row, so deleting the job still cascades, while
    -- deleting this one run is refused rather than taking every other run's
    -- results for the job with it.
    source_run_id INTEGER NOT NULL,
    input_details JSONB NOT NULL CHECK (jsonb_typeof(input_details) = 'object'),
    created_on TIMESTAMP NOT NULL DEFAULT now(),
    PRIMARY KEY (job_id, correlation_id),
    FOREIGN KEY (source_run_id, job_id) REFERENCES public.run (id, job_id) ON DELETE NO ACTION
);

CREATE INDEX student_input_details_source_run_id_idx
    ON public.student_input_details (source_run_id);

-- One row per (input group, run): the outcome of one matching attempt.
-- Exists even when that attempt returned no suggestions.
CREATE TABLE public.student_match_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id INTEGER NOT NULL,
    correlation_id TEXT NOT NULL CHECK (length(correlation_id) BETWEEN 1 AND 128),
    run_id INTEGER NOT NULL,
    created_on TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (job_id, correlation_id, run_id),
    FOREIGN KEY (job_id, correlation_id)
        REFERENCES public.student_input_details (job_id, correlation_id) ON DELETE CASCADE,
    FOREIGN KEY (run_id, job_id) REFERENCES public.run (id, job_id) ON DELETE CASCADE
);

CREATE INDEX student_match_result_run_id_idx ON public.student_match_result (run_id);

-- One row per possible match returned for a result. (result_id, ordinal) is an
-- immutable position within that result, not a student identity.
CREATE TABLE public.student_match_suggestion (
    result_id BIGINT NOT NULL REFERENCES public.student_match_result (id) ON DELETE CASCADE,
    ordinal INTEGER NOT NULL CHECK (ordinal >= 0),
    student_unique_id TEXT NOT NULL CHECK (length(student_unique_id) > 0),
    roster_details JSONB NOT NULL CHECK (jsonb_typeof(roster_details) = 'object'),
    score NUMERIC NOT NULL,
    PRIMARY KEY (result_id, ordinal)
);

CREATE INDEX student_match_suggestion_student_unique_id_idx
    ON public.student_match_suggestion (student_unique_id);
