---
# "realm" basically means User Pool or Tenant
realm: example
displayName: Example
ssoSessionMaxLifespan: 7776000
enabled: true

clientScopes:
  - name: "create:jobs"
    protocol: openid-connect
    attributes:
      "include.in.token.scope": "true"
  - name: "partner:ea"
    protocol: openid-connect
    attributes:
      "include.in.token.scope": "true"

clients:
  # UI login (authorization code flow)
  - clientId: runway-local
    name: 'Runway Local Dev'
    enabled: true
    rootUrl: http://localhost:3333
    adminUrl: http://localhost:3333
    baseUrl: http://localhost:3333
    clientAuthenticatorType: client-secret
    secret: big-secret-123
    redirectUris:
      - http://localhost:3333/api/auth/callback/local-keycloak
    webOrigins:
      - http://localhost:4200
    protocolMappers:
      # This is a small window into a very big and important
      # feature, which is the mapping of nearly-arbitrary
      # data from various sources into the tokens which are
      # sent to client applications. This one just exposes
      # the username of the impersonating user, if in fact
      # the token is for a user who's being impersonated.
      - name: Impersonator Username
        protocol: openid-connect
        protocolMapper: oidc-usersessionmodel-note-mapper
        consentRequired: false
        config:
          user.session.note: IMPERSONATOR_USERNAME
          id.token.claim: 'true'
          access.token.claim: 'true'
          claim.name: impersonator.username
          jsonType.label: String
      # Hardcoding tenant per client. This is probably not what real prod IdPs
      # would do, but works locally and it's probably better than using
      # `iss` or some other exist claim that's not really a tenant code.
      - name: Tenant Code
        protocol: openid-connect
        protocolMapper: oidc-hardcoded-claim-mapper
        consentRequired: false
        config:
          claim.name : tenant_code
          claim.value : runway-local-example-tenant
          id.token.claim: 'true'
          access.token.claim: 'true'
          claim.name: tenant_code
          jsonType.label: String
    attributes:
      post.logout.redirect.uris: http://localhost:4200* 

  # External API (client credentials flow)
  - clientId: runway-api
    name: 'Runway External API'
    enabled: true
    clientAuthenticatorType: client-secret
    secret: api-secret-123
    serviceAccountsEnabled: true
    standardFlowEnabled: false
    directAccessGrantsEnabled: false
    defaultClientScopes:
      - "create:jobs"
      - "partner:ea"
    protocolMappers:
      # The app validates the aud claim, so we need to inject it.
      # Value must match OAUTH2_AUDIENCE.
      - name: API Audience
        protocol: openid-connect
        protocolMapper: oidc-audience-mapper
        consentRequired: false
        config:
          included.custom.audience: "runway-local"
          id.token.claim: "false"
          access.token.claim: "true"

users:
  - username: dev
    credentials:
      - type: password
        value: dev
    email: dev@example.com
    enabled: true
    firstName: Dev
    lastName: D'Evdeverson
    emailVerified: true
  - username: admin
    credentials:
      - type: password
        value: admin
    email: admin@example.com
    enabled: true
    firstName: Admin
    lastName: McAdminFace
    emailVerified: true
