/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OdsConfigsImport } from './routes/ods-configs'
import { Route as AssessmentsImport } from './routes/assessments'
import { Route as IndexImport } from './routes/index'
import { Route as OdsConfigsIndexImport } from './routes/ods-configs.index'
import { Route as AssessmentsIndexImport } from './routes/assessments.index'
import { Route as OdsConfigsNewImport } from './routes/ods-configs.new'
import { Route as OdsConfigsOdsConfigIdImport } from './routes/ods-configs.$odsConfigId'
import { Route as AssessmentsNewImport } from './routes/assessments.new'
import { Route as AssessmentsAssessmentIdImport } from './routes/assessments.$assessmentId'
import { Route as OdsConfigsOdsConfigIdIndexImport } from './routes/ods-configs.$odsConfigId.index'
import { Route as AssessmentsAssessmentIdIndexImport } from './routes/assessments.$assessmentId.index'
import { Route as OdsConfigsNewConnectionImport } from './routes/ods-configs.new.connection'
import { Route as OdsConfigsOdsConfigIdDescriptorsImport } from './routes/ods-configs.$odsConfigId.descriptors'
import { Route as OdsConfigsOdsConfigIdConnectionImport } from './routes/ods-configs.$odsConfigId.connection'
import { Route as AssessmentsAssessmentIdSubmittedImport } from './routes/assessments.$assessmentId.submitted'

// Create/Update Routes

const OdsConfigsRoute = OdsConfigsImport.update({
  path: '/ods-configs',
  getParentRoute: () => rootRoute,
} as any)

const AssessmentsRoute = AssessmentsImport.update({
  path: '/assessments',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OdsConfigsIndexRoute = OdsConfigsIndexImport.update({
  path: '/',
  getParentRoute: () => OdsConfigsRoute,
} as any)

const AssessmentsIndexRoute = AssessmentsIndexImport.update({
  path: '/',
  getParentRoute: () => AssessmentsRoute,
} as any)

const OdsConfigsNewRoute = OdsConfigsNewImport.update({
  path: '/new',
  getParentRoute: () => OdsConfigsRoute,
} as any)

const OdsConfigsOdsConfigIdRoute = OdsConfigsOdsConfigIdImport.update({
  path: '/$odsConfigId',
  getParentRoute: () => OdsConfigsRoute,
} as any)

const AssessmentsNewRoute = AssessmentsNewImport.update({
  path: '/new',
  getParentRoute: () => AssessmentsRoute,
} as any)

const AssessmentsAssessmentIdRoute = AssessmentsAssessmentIdImport.update({
  path: '/$assessmentId',
  getParentRoute: () => AssessmentsRoute,
} as any)

const OdsConfigsOdsConfigIdIndexRoute = OdsConfigsOdsConfigIdIndexImport.update(
  {
    path: '/',
    getParentRoute: () => OdsConfigsOdsConfigIdRoute,
  } as any,
)

const AssessmentsAssessmentIdIndexRoute =
  AssessmentsAssessmentIdIndexImport.update({
    path: '/',
    getParentRoute: () => AssessmentsAssessmentIdRoute,
  } as any)

const OdsConfigsNewConnectionRoute = OdsConfigsNewConnectionImport.update({
  path: '/connection',
  getParentRoute: () => OdsConfigsNewRoute,
} as any)

const OdsConfigsOdsConfigIdDescriptorsRoute =
  OdsConfigsOdsConfigIdDescriptorsImport.update({
    path: '/descriptors',
    getParentRoute: () => OdsConfigsOdsConfigIdRoute,
  } as any)

const OdsConfigsOdsConfigIdConnectionRoute =
  OdsConfigsOdsConfigIdConnectionImport.update({
    path: '/connection',
    getParentRoute: () => OdsConfigsOdsConfigIdRoute,
  } as any)

const AssessmentsAssessmentIdSubmittedRoute =
  AssessmentsAssessmentIdSubmittedImport.update({
    path: '/submitted',
    getParentRoute: () => AssessmentsAssessmentIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsImport
      parentRoute: typeof rootRoute
    }
    '/ods-configs': {
      id: '/ods-configs'
      path: '/ods-configs'
      fullPath: '/ods-configs'
      preLoaderRoute: typeof OdsConfigsImport
      parentRoute: typeof rootRoute
    }
    '/assessments/$assessmentId': {
      id: '/assessments/$assessmentId'
      path: '/$assessmentId'
      fullPath: '/assessments/$assessmentId'
      preLoaderRoute: typeof AssessmentsAssessmentIdImport
      parentRoute: typeof AssessmentsImport
    }
    '/assessments/new': {
      id: '/assessments/new'
      path: '/new'
      fullPath: '/assessments/new'
      preLoaderRoute: typeof AssessmentsNewImport
      parentRoute: typeof AssessmentsImport
    }
    '/ods-configs/$odsConfigId': {
      id: '/ods-configs/$odsConfigId'
      path: '/$odsConfigId'
      fullPath: '/ods-configs/$odsConfigId'
      preLoaderRoute: typeof OdsConfigsOdsConfigIdImport
      parentRoute: typeof OdsConfigsImport
    }
    '/ods-configs/new': {
      id: '/ods-configs/new'
      path: '/new'
      fullPath: '/ods-configs/new'
      preLoaderRoute: typeof OdsConfigsNewImport
      parentRoute: typeof OdsConfigsImport
    }
    '/assessments/': {
      id: '/assessments/'
      path: '/'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AssessmentsIndexImport
      parentRoute: typeof AssessmentsImport
    }
    '/ods-configs/': {
      id: '/ods-configs/'
      path: '/'
      fullPath: '/ods-configs/'
      preLoaderRoute: typeof OdsConfigsIndexImport
      parentRoute: typeof OdsConfigsImport
    }
    '/assessments/$assessmentId/submitted': {
      id: '/assessments/$assessmentId/submitted'
      path: '/submitted'
      fullPath: '/assessments/$assessmentId/submitted'
      preLoaderRoute: typeof AssessmentsAssessmentIdSubmittedImport
      parentRoute: typeof AssessmentsAssessmentIdImport
    }
    '/ods-configs/$odsConfigId/connection': {
      id: '/ods-configs/$odsConfigId/connection'
      path: '/connection'
      fullPath: '/ods-configs/$odsConfigId/connection'
      preLoaderRoute: typeof OdsConfigsOdsConfigIdConnectionImport
      parentRoute: typeof OdsConfigsOdsConfigIdImport
    }
    '/ods-configs/$odsConfigId/descriptors': {
      id: '/ods-configs/$odsConfigId/descriptors'
      path: '/descriptors'
      fullPath: '/ods-configs/$odsConfigId/descriptors'
      preLoaderRoute: typeof OdsConfigsOdsConfigIdDescriptorsImport
      parentRoute: typeof OdsConfigsOdsConfigIdImport
    }
    '/ods-configs/new/connection': {
      id: '/ods-configs/new/connection'
      path: '/connection'
      fullPath: '/ods-configs/new/connection'
      preLoaderRoute: typeof OdsConfigsNewConnectionImport
      parentRoute: typeof OdsConfigsNewImport
    }
    '/assessments/$assessmentId/': {
      id: '/assessments/$assessmentId/'
      path: '/'
      fullPath: '/assessments/$assessmentId/'
      preLoaderRoute: typeof AssessmentsAssessmentIdIndexImport
      parentRoute: typeof AssessmentsAssessmentIdImport
    }
    '/ods-configs/$odsConfigId/': {
      id: '/ods-configs/$odsConfigId/'
      path: '/'
      fullPath: '/ods-configs/$odsConfigId/'
      preLoaderRoute: typeof OdsConfigsOdsConfigIdIndexImport
      parentRoute: typeof OdsConfigsOdsConfigIdImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AssessmentsRoute: AssessmentsRoute.addChildren({
    AssessmentsAssessmentIdRoute: AssessmentsAssessmentIdRoute.addChildren({
      AssessmentsAssessmentIdSubmittedRoute,
      AssessmentsAssessmentIdIndexRoute,
    }),
    AssessmentsNewRoute,
    AssessmentsIndexRoute,
  }),
  OdsConfigsRoute: OdsConfigsRoute.addChildren({
    OdsConfigsOdsConfigIdRoute: OdsConfigsOdsConfigIdRoute.addChildren({
      OdsConfigsOdsConfigIdConnectionRoute,
      OdsConfigsOdsConfigIdDescriptorsRoute,
      OdsConfigsOdsConfigIdIndexRoute,
    }),
    OdsConfigsNewRoute: OdsConfigsNewRoute.addChildren({
      OdsConfigsNewConnectionRoute,
    }),
    OdsConfigsIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/assessments",
        "/ods-configs"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/assessments": {
      "filePath": "assessments.tsx",
      "children": [
        "/assessments/$assessmentId",
        "/assessments/new",
        "/assessments/"
      ]
    },
    "/ods-configs": {
      "filePath": "ods-configs.tsx",
      "children": [
        "/ods-configs/$odsConfigId",
        "/ods-configs/new",
        "/ods-configs/"
      ]
    },
    "/assessments/$assessmentId": {
      "filePath": "assessments.$assessmentId.tsx",
      "parent": "/assessments",
      "children": [
        "/assessments/$assessmentId/submitted",
        "/assessments/$assessmentId/"
      ]
    },
    "/assessments/new": {
      "filePath": "assessments.new.tsx",
      "parent": "/assessments"
    },
    "/ods-configs/$odsConfigId": {
      "filePath": "ods-configs.$odsConfigId.tsx",
      "parent": "/ods-configs",
      "children": [
        "/ods-configs/$odsConfigId/connection",
        "/ods-configs/$odsConfigId/descriptors",
        "/ods-configs/$odsConfigId/"
      ]
    },
    "/ods-configs/new": {
      "filePath": "ods-configs.new.tsx",
      "parent": "/ods-configs",
      "children": [
        "/ods-configs/new/connection"
      ]
    },
    "/assessments/": {
      "filePath": "assessments.index.tsx",
      "parent": "/assessments"
    },
    "/ods-configs/": {
      "filePath": "ods-configs.index.tsx",
      "parent": "/ods-configs"
    },
    "/assessments/$assessmentId/submitted": {
      "filePath": "assessments.$assessmentId.submitted.tsx",
      "parent": "/assessments/$assessmentId"
    },
    "/ods-configs/$odsConfigId/connection": {
      "filePath": "ods-configs.$odsConfigId.connection.tsx",
      "parent": "/ods-configs/$odsConfigId"
    },
    "/ods-configs/$odsConfigId/descriptors": {
      "filePath": "ods-configs.$odsConfigId.descriptors.tsx",
      "parent": "/ods-configs/$odsConfigId"
    },
    "/ods-configs/new/connection": {
      "filePath": "ods-configs.new.connection.tsx",
      "parent": "/ods-configs/new"
    },
    "/assessments/$assessmentId/": {
      "filePath": "assessments.$assessmentId.index.tsx",
      "parent": "/assessments/$assessmentId"
    },
    "/ods-configs/$odsConfigId/": {
      "filePath": "ods-configs.$odsConfigId.index.tsx",
      "parent": "/ods-configs/$odsConfigId"
    }
  }
}
ROUTE_MANIFEST_END */
